### ISSUE TITLE
Fix Boilerplate Files

### ISSUE THREAD

**Issue by FerranMarin** [Axie-Management-Team/axie-automatic-payments#1]
Some files that came with boiler plate need to be removed  modified. We of course want to acknowleadge them but we are a separate project. One example is the code of conduct file.

**Comment by blanxii** [comment]
Updated code of conduct and remove their donations file. Of course we'll need to investigate what's missing

**Comment by FerranMarin** [comment]
I'll have a deeper look tomorrow. See what missing.

**Comment by FerranMarin** [comment]
Done.
